// react_client/src/components/Footer/Footer.js
import React from "react";

const style = {
    backgroundColor: "#F8F8F8",
    borderTop: "1px solid #E7E7E7",
    textAlign: "center",
    padding: "20px",
    position: "fixed",
    left: "0",
    bottom: "0",
    height: "60px",
    width: "100%"
};

const Footer = () => {
    const currentDate = new Date();

    return (
        <div style={style}>Copyright &copy; React Example {currentDate.getFullYear()}</div>
    );
}

export default Footer

// vue_client/src/components/Footer.vue
<style scoped>

.footer {
  flex-shrink: 0;
  text-align: center;
  padding: 20px;
  position: fixed;
  left: 0;
  bottom: 0;
  height: 60px;
  width: 100%;
}

</style>
<template>
  <footer class="footer">Copyright &copy; Vue Example {{ new Date().getFullYear() }}</footer>
</template>
<script>
export default {
name: "Footer"
}
</script>
